### ISSUE TITLE
French localization - Stamp text is missing the accents

### ISSUE THREAD

**Issue by Tailszefox** [dukope/BugsPlease#14]
![papers5](https://f.cloud.github.com/assets/890677/2054836/261f91bc-8abb-11e3-934c-88ccb76d984b.png)

The stamps themselves have proper accents, but the text they...stamp is missing them. It should be "ENTRÉE VALIDÉE" and "ENTRÉE REFUSÉE".

Not putting accents when they are needed is considered a spelling mistake in French, but I understand if they had to be removed because of space constraint. If there's a way to add them, though, that would be a nice little addition.

**Comment by dukope** [comment]
Is this an improvement?

![frenchstamps](https://f.cloud.github.com/assets/5263143/2056983/e3489b5a-8aff-11e3-8980-4e7f8d35a530.png)

**Comment by Tailszefox** [comment]
Definitely. Though if I can nitpick even more, it seems like the "É" in "VALIDÉE" is actually an "È", that is, it looks like it has a grave accent instead of an acute accent. That may just be due to the limited space and my bad eyesight, though, so if it is indeed already an acute accent, then that is more than enough.

**Comment by dukope** [comment]
It's not your eyesight, there's just no pixels left to distinguish the two accents. :)

Does it help if I remove one pixel on the left of the accent?

![frenchstamps2](https://f.cloud.github.com/assets/5263143/2057134/e447cf3a-8b0e-11e3-83ff-b861a6967215.png)

**Comment by AlainDellepiane** [comment]
Lucas, you might want to double check this with the translator, as omitting accents in all caps is a stylistic choice for French

https://www.google.co.jp/search?q=entr%C3%A9e+interdite&source=lnms&tbm=isch&sa=X&ei=BZ3sUvqBI4LIkwW_rIHoBQ&ved=0CAkQ_AUoAQ&biw=1378&bih=792

**Comment by Tailszefox** [comment]
@AlainDellepiane I see where your confusion comes from, but it's not stylistic choice, it's a spelling mistake that is unfortunately "accepted" because a lot of people have no idea how to put accents on capital letters using a standard French keyboard. The Académie Française, the "authority" who defines the French language, points out on their website [that it is indispensable to put them no matter what](http://translate.google.fr/translate?sl=fr&tl=en&js=n&prev=_t&hl=fr&ie=UTF-8&u=http%3A%2F%2Fwww.academie-francaise.fr%2Fla-langue-francaise%2Fquestions-de-langue%235_strong-em-accentuation-des-majuscules-em-strong).

Even then, the vast majority of the text written in capital letters in the game does have accents, so for the sake of consistency, I think it's better if those have accents too.

@dukope I'm sorry, it still seems for me that the second É is an È.

Is it possible to do it like in that mockup? The first "row" has three pixels, and the second has six pixels.

![accents](https://f.cloud.github.com/assets/890677/2057167/bcb3d056-8b11-11e3-9c6b-8833cb05698f.png)

**Comment by dukope** [comment]
The images I've posted are at 2x resolution, that subpixel editing is not possible. If the only remaining problem is the É in VALIDÉE, then I can chop the E above to clarify the slope:

![frenchstamps3](https://f.cloud.github.com/assets/5263143/2057178/fbd12e5e-8b12-11e3-9b6b-b82d5c10d417.png)

I have good faith in the localizers but I put some serious constraints on them for images like this. In some cases they may have felt it unimportant enough to fight back against the restrictions. If there's something particular like this that someone feels strongly about it then I'm ok to tweak the images a bit. 

What I want to avoid is a stylistic conflict with other treatments in the French localization. @Tailszefox, if you see that WordsOfMagic has followed a certain consistency by leaving these accents out (although it sounds like they use accents wherever possible), then I'll probably waive this issue.

**Comment by dukope** [comment]
Actually I can even add a pixel there now:

![frenchstamps4](https://f.cloud.github.com/assets/5263143/2057209/71936322-8b14-11e3-9e2c-7e0b9e0329a1.png)

**Comment by Tailszefox** [comment]
Ah, alright, if it's only one pixel in height in game, then yeah, no way to do it like I tried.

And of course, I'm not trying to disparage the work of the translators, they did an excellent work especially considering the constraints they had to work with. But as I said, not adding those accents would actually be inconsistent with what they did with pretty much everything else: they put careful attention in making sure every other text written in all caps has accents (which is, as I said, actually pretty unusual and really commendable, because most people don't bother with that), and that seems to be the only exception, which is why I think it's more consistent to add them here if possible.

And yeah, your second image looks much better. Thank you for taking the time to work on that small issue.

**Comment by dukope** [comment]
Fixed in 1.1.56

**Comment by Tailszefox** [comment]
Hm...I updated to 1.1.56 (the main menu says "1.1.56S") but the stamps are still showing up the way they did before, without any accent. Did you decide to waive the issue for now, or is there something else to do to see the fix in action? I do see some other issues fixed, like the spacing issue in the rule book I reported, so I assume I have the right version.

**Comment by dukope** [comment]
Nope, you're right. I actually fixed this but it looks like the localization export had a hiccup. I'll make sure this fix gets in the next build.

**Comment by WordsOfMagic** [comment]
We usually use accents on caps when possible because it makes more sense, but we're also being pragmatic.

That was a conscious choice because we knew that a) it would look fairly bad or confusing b) it didn't strike me odd that a stamp from 1982 would omit accents (even in the 1990s, many books by major authors sill omited accents on capital letters). So it worked in context and we didn't think it would be worth the trouble.

**Comment by Tailszefox** [comment]
Then again, this is a game where you have scanner that allows you to see under people's clothes, so it may be a bit anachronistic here in there. As such, I don't think the stamps having accents is an issue. I think the solution found here looks alright, neither bad nor confusing, but I can understand how it didn't look worth the trouble.

I realize I'm nitpicking here, the game won't be any worse if those stamps don't have proper accents, but I figure given the quality of the translation, we may as well go the extra mile as long as we're able to without it having an negative effect.

**Comment by WordsOfMagic** [comment]
Sure, the current version looks OK!
It's just that, when faced with hundreds of problems, we had to prioritize. :-)

Anyway, glad to see that you're happy with our translations! Thanks a lot.

**Comment by Tailszefox** [comment]
Of course, as I said, that's minor nitpicking. Now's the right time for it I think: considering this is the final beta testing phase (if all goes well), it's the ideal time to fix all the little bits and bobs, which obviously can only be done once the most important parts of the translation are done, thank to your team.

So, again, please don't take any of what I'm saying as me disparaging your work or saying you missed stuff, I'm focusing on what little is left to make everything more than perfect.

**Comment by dukope** [comment]
Fixed for real in 1.1.57
